services:
  postgres:
    image: postgres:16
    container_name: postgres-server
    env_file:
      - .dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis-server
    env_file:
      - .dev.env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  server:
    build: .
    container_name: server
    env_file:
      - .dev.env
    volumes:
      - .:/app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: air
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
